import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { ChatSection } from "../../../modules/chat";
import { AppLayout } from "../../../modules/layout";

const Chat: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        {router.isReady && (
          <ChatSection id={Number.parseInt(router.query.id as string)} />
        )}
      </AppLayout>
    </div>
  );
};

export default Chat;
