import { Paper, Space, Title } from "@mantine/core";
import { NextPage } from "next";
import Head from "next/head";
import { LoginForm } from "../../modules/auth";
import { AuthLayout } from "../../modules/layout/AuthLayout";

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <Paper radius="md" p="xl" withBorder sx={{ width: 400 }}>
          <Title>Login</Title>
          <Space h="lg" />
          <LoginForm onSubmit={(values) => console.log(values)} />
        </Paper>
      </AuthLayout>
    </div>
  );
};

export default Login;
