import { Paper, Space, Title } from "@mantine/core";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { LoginForm } from "../../modules/auth";
import { AuthLayout } from "../../modules/layout/AuthLayout";
import { login } from "../../services";
import { useCurrentUser } from "../../stores/useCurrentUser";
import { LoginFields } from "../../types/interfaces";

const Login: NextPage = () => {
  const router = useRouter();
  const { setLoggedIn } = useCurrentUser();

  const callLogin = async (values: LoginFields) => {
    const data = await login(values);
    localStorage.setItem("access_token", data.accessToken);
    setLoggedIn(Number.parseInt(data.id));
    router.push("/");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <Paper radius="md" p="xl" withBorder sx={{ width: 400 }}>
          <Title>Login</Title>
          <Space h="lg" />
          <LoginForm onSubmit={callLogin} />
        </Paper>
      </AuthLayout>
    </div>
  );
};

export default Login;
