import { Box } from "@mantine/core";
import { NextPage } from "next";
import Head from "next/head";
import { RegisterForm } from "../../modules/auth";

const Register: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box p="xl">
          <RegisterForm onSubmit={(values) => console.log(values)} />
        </Box>
      </main>
    </div>
  );
};

export default Register;
