import type { NextPage } from "next";
import Head from "next/head";
import { Channel } from "../modules/channel";
import { AppLayout } from "../modules/layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Channel />
      </AppLayout>
    </div>
  );
};

export default Home;
